### ISSUE TITLE
Blankscreen after update (ubuntu 16.04)

### ISSUE THREAD

**Issue by nayra42** [MysticRyuujin/guac-install#69]
I have a blank screen after update, I have tried, rolled back to snapshot and tried a second time to be sure my root password is right.  Looks like something with the DB?  Ideas? 

My catalina log reads as follows:

17:28:18.403 [http-bio-8080-exec-10] ERROR o.a.g.rest.RESTExceptionWrapper - Unexpected internal error:
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'guacamole_user.username' in
 'field list'
### SQL: SELECT             guacamole_user.user_id,             guacamole_user.username,             password_hash,             password_sa
lt,             password_date,             disabled,             expired,             access_window_start,             access_window_end,
           valid_from,             valid_until,             timezone,             full_name,             email_address,             organiz
ation,             organizational_role,             MAX(start_date) AS last_active         FROM guacamole_user         LEFT JOIN guacamole_
user_history ON guacamole_user_history.user_id = guacamole_user.user_id         WHERE             guacamole_user.username = ?         GROUP
 BY guacamole_user.user_id
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'guacamole_user.username' in 'field list'
Jan 23, 2019 5:28:18 PM com.sun.jersey.spi.container.ContainerResponse logException
SEVERE: Mapped exception to response: 500 (Internal Server Error)
org.apache.guacamole.rest.APIException
        at org.apache.guacamole.rest.RESTExceptionWrapper.invoke(RESTExceptionWrapper.java:202)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourc
eMethodDispatchProvider.java:185)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)

**Comment by MysticRyuujin** [comment]
Did you originally install with my script?

**Comment by nayra42** [comment]
Yes, and i upgraded from 0.9.13 to 0.9.14 with your previous update.  I do use Duo and did see something about that in there too, upgrading that extension to make sure right now...
